apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-u0k0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-u0k0@sha256:a48ae09c4b96b022ed22ebcc20437147f95445904cc3549584cf01e265edd165
        name: my-nodejs
        resources: {}
status: {}
